const SUCCESS_MESSAGE = {
    CREATED: 'Created successfully',
    UPDATED: 'Updated successfully',
    DELETED: 'Deleted successfully',
    FETCHED: 'Fetched successfully',
    FETCHED_ALL: 'Fetched all successfully',
    FETCHED_ONE: 'Fetched one successfully',
    FETCHED_BY_ID: 'Fetched by id successfully',
    FETCHED_BY_FIELD: 'Fetched by field successfully',
    FETCHED_BY_QUERY: 'Fetched by query successfully',
    FETCHED_BY_PAGE: 'Fetched by page successfully',
    FETCHED_BY_LIMIT: 'Fetched by limit successfully',
    FETCHED_BY_SORT: 'Fetched by sort successfully',
    FETCHED_BY_FILTER: 'Fetched by filter successfully',
    FETCHED_BY_SEARCH: 'Fetched by search successfully',
    FETCHED_BY_DATE: 'Fetched by date successfully',
    FETCHED_BY_DATE_RANGE: 'Fetched by date range successfully',
    FETCHED_BY_DATE_TIME: 'Fetched by date time'
};

export const ERROR_MESSAGE = {
    CREATED: 'Create failed',
    UPDATED: 'Update failed',
    DELETED: 'Delete failed',
    FETCHED: 'Fetch failed',
    FETCHED_ALL: 'Fetch all failed',
    FETCHED_ONE: 'Fetch one failed',
    FETCHED_BY_ID: 'Fetch by id failed',
    FETCHED_BY_FIELD: 'Fetch by field failed',
    FETCHED_BY_QUERY: 'Fetch by query failed',
    FETCHED_BY_PAGE: 'Fetch by page failed',
    FETCHED_BY_LIMIT: 'Fetch by limit failed',
    FETCHED_BY_SORT: 'Fetch by sort failed',
    FETCHED_BY_FILTER: 'Fetch by filter failed',
    FETCHED_BY_SEARCH: 'Fetch by search failed',
    FETCHED_BY_DATE: 'Fetch by date failed',
    FETCHED_BY_DATE_RANGE: 'Fetch by date range failed',
    FETCHED_BY_DATE_TIME: 'Fetch by date time failed',
    SOMETHING_WENT_WRONG: 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    };